/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControladorProductos;
import controller.InventarioXML;
import controller.RenderLista;
import model.Usuario;
import javax.swing.DefaultListModel;
import model.Productos;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Jessica
 */
public class ListaBusqueda extends javax.swing.JFrame {

    InventarioXML pro = new InventarioXML();
    ArrayList<ImageIcon> resultado = new ArrayList();
    DefaultListModel modelo = new DefaultListModel();
    Usuario usuario;

    /**
     * Creates new form ListaBusqueda
     */
    public ListaBusqueda() {
        initComponents();
    }

    public ListaBusqueda(Usuario usu, String dato) {
        initComponents();
        usuario = usu;
         if (usuario != null) {
            LabelIngresa.setVisible(false);
            LabelUsuario.setText(usuario.getSeudonimo());
        } else {
            LabelIngresa.setVisible(true);
            LabelUsuario.setVisible(false);
        }
          resultado = ControladorProductos.llenaLista(pro,lista,modelo ,dato);
          lista.setCellRenderer(new RenderLista(resultado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        productotxt = new javax.swing.JTextField();
        LabelIngresa = new javax.swing.JLabel();
        LabelBuscar = new javax.swing.JLabel();
        LabelVolver1 = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();
        botonDetalle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productotxtActionPerformed(evt);
            }
        });
        jPanel4.add(productotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 350, 40));

        LabelIngresa.setForeground(new java.awt.Color(102, 102, 102));
        LabelIngresa.setText("Ingresa");
        LabelIngresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelIngresaMouseClicked(evt);
            }
        });
        jPanel4.add(LabelIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 25, -1, 30));

        LabelBuscar.setForeground(new java.awt.Color(102, 102, 102));
        LabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/buscar.png"))); // NOI18N
        LabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBuscarMouseClicked(evt);
            }
        });
        jPanel4.add(LabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 50, 40));

        LabelVolver1.setForeground(new java.awt.Color(102, 102, 102));
        LabelVolver1.setText("Volver");
        LabelVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelVolver1MouseClicked(evt);
            }
        });
        jPanel4.add(LabelVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, -1, 30));

        LabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        LabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/perfil.png"))); // NOI18N
        LabelUsuario.setText("Usuario");
        jPanel4.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("Wonderland");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lista.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(lista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 870, 320));

        botonDetalle.setBackground(new java.awt.Color(0, 0, 102));
        botonDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonDetalle.setForeground(new java.awt.Color(255, 255, 255));
        botonDetalle.setText("Ver detalles del Producto");
        botonDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(botonDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productotxtActionPerformed

    private void LabelIngresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelIngresaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LabelIngresaMouseClicked

    private void LabelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBuscarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LabelBuscarMouseClicked

    private void LabelVolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelVolver1MouseClicked
        // TODO add your handling code here:
        Principal control2 = new Principal(usuario);
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelVolver1MouseClicked

    
       private void jList1ValueChanged(int index) {
        //int index = listaProductos.getSelectedIndex();
        Productos objProducto = (Productos) modelo.getElementAt(index);
        DatosProducto control2 = new DatosProducto(objProducto, usuario);
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }
    private void botonDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetalleActionPerformed
        // TODO add your handling code here:
        jList1ValueChanged(lista.getSelectedIndex());
    }//GEN-LAST:event_botonDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelIngresa;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel LabelVolver1;
    private javax.swing.JButton botonDetalle;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista;
    private javax.swing.JTextField productotxt;
    // End of variables declaration//GEN-END:variables
}
