/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Usuario;
import controller.InventarioXML;


/**
 *
 * @author Jessica
 */
public class Principal extends javax.swing.JFrame {

    Usuario usuario;
    InventarioXML DatPro = new InventarioXML();

    public Principal() {
        initComponents();
        LabelIngresa.setVisible(true);
        LabelUsuario.setVisible(false);

    }

    public Principal(Usuario usu) {
        initComponents();
        usuario = usu;
        if (usuario != null) {
            LabelIngresa.setVisible(false);
            LabelUsuario.setText(usuario.getSeudonimo());
        } else {
            LabelIngresa.setVisible(true);
            LabelUsuario.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        productotxt = new javax.swing.JTextField();
        LabelIngresa = new javax.swing.JLabel();
        LabelBuscar = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Wonderland");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 40));

        productotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productotxtActionPerformed(evt);
            }
        });
        jPanel4.add(productotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 350, 40));

        LabelIngresa.setForeground(new java.awt.Color(102, 102, 102));
        LabelIngresa.setText("Ingresa");
        LabelIngresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelIngresaMouseClicked(evt);
            }
        });
        jPanel4.add(LabelIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 25, 80, 30));

        LabelBuscar.setForeground(new java.awt.Color(102, 102, 102));
        LabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/buscar.png"))); // NOI18N
        LabelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBuscarMouseClicked(evt);
            }
        });
        jPanel4.add(LabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 50, 40));

        LabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        LabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/perfil.png"))); // NOI18N
        LabelUsuario.setText("Usuario");
        jPanel4.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrate Ya !");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 330, 150, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("¿No tienes cuenta?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 300, 150, 22);

        l10.setBackground(new java.awt.Color(255, 255, 255));
        l10.setForeground(new java.awt.Color(51, 51, 51));
        l10.setText("Hogar y Muebles");
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        jPanel1.add(l10);
        l10.setBounds(380, 260, 149, 16);

        l9.setBackground(new java.awt.Color(255, 255, 255));
        l9.setForeground(new java.awt.Color(51, 51, 51));
        l9.setText("Electrodomesticos");
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        jPanel1.add(l9);
        l9.setBounds(380, 240, 150, 16);

        l8.setBackground(new java.awt.Color(255, 255, 255));
        l8.setForeground(new java.awt.Color(51, 51, 51));
        l8.setText("Deportes");
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        jPanel1.add(l8);
        l8.setBounds(380, 220, 149, 16);

        l7.setBackground(new java.awt.Color(255, 255, 255));
        l7.setForeground(new java.awt.Color(51, 51, 51));
        l7.setText("Consolas y Videojuegos");
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        jPanel1.add(l7);
        l7.setBounds(380, 200, 160, 16);

        l6.setBackground(new java.awt.Color(255, 255, 255));
        l6.setForeground(new java.awt.Color(51, 51, 51));
        l6.setText("Computacion");
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        jPanel1.add(l6);
        l6.setBounds(380, 180, 130, 16);

        L1.setBackground(new java.awt.Color(255, 255, 255));
        L1.setForeground(new java.awt.Color(51, 51, 51));
        L1.setText("Accesorios para Vehiculos");
        L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                L1MouseClicked(evt);
            }
        });
        jPanel1.add(L1);
        L1.setBounds(110, 180, 160, 16);

        l2.setBackground(new java.awt.Color(255, 255, 255));
        l2.setForeground(new java.awt.Color(51, 51, 51));
        l2.setText("Animales y Mascotas");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        jPanel1.add(l2);
        l2.setBounds(110, 200, 150, 16);

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setForeground(new java.awt.Color(51, 51, 51));
        l3.setText("Bebes");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        jPanel1.add(l3);
        l3.setBounds(110, 220, 40, 16);

        l4.setBackground(new java.awt.Color(255, 255, 255));
        l4.setForeground(new java.awt.Color(51, 51, 51));
        l4.setText("Camaras y Acesorios");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        jPanel1.add(l4);
        l4.setBounds(110, 240, 150, 16);

        l5.setBackground(new java.awt.Color(255, 255, 255));
        l5.setForeground(new java.awt.Color(51, 51, 51));
        l5.setText("Celulares y Telefonos");
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        jPanel1.add(l5);
        l5.setBounds(110, 260, 150, 16);

        l15.setBackground(new java.awt.Color(255, 255, 255));
        l15.setForeground(new java.awt.Color(51, 51, 51));
        l15.setText("Otras Categorias");
        jPanel1.add(l15);
        l15.setBounds(620, 260, 190, 16);

        l14.setBackground(new java.awt.Color(255, 255, 255));
        l14.setForeground(new java.awt.Color(51, 51, 51));
        l14.setText("Salud y Belleza");
        l14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l14MouseClicked(evt);
            }
        });
        jPanel1.add(l14);
        l14.setBounds(620, 240, 180, 16);

        l13.setBackground(new java.awt.Color(255, 255, 255));
        l13.setForeground(new java.awt.Color(51, 51, 51));
        l13.setText("Ropa, Zapato y Acesorios");
        l13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l13MouseClicked(evt);
            }
        });
        jPanel1.add(l13);
        l13.setBounds(620, 220, 190, 16);

        l12.setBackground(new java.awt.Color(255, 255, 255));
        l12.setForeground(new java.awt.Color(51, 51, 51));
        l12.setText("Libros, Musica y Peliculas");
        l12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l12MouseClicked(evt);
            }
        });
        jPanel1.add(l12);
        l12.setBounds(620, 200, 190, 16);

        l11.setBackground(new java.awt.Color(255, 255, 255));
        l11.setForeground(new java.awt.Color(51, 51, 51));
        l11.setText("Instrumentos Musicales");
        l11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l11MouseClicked(evt);
            }
        });
        jPanel1.add(l11);
        l11.setBounds(620, 180, 180, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Categorias");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 130, 90, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tu mejor opción para compras, registrarse es gratis");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 70, 320, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("¡Encuentra lo que Buscas!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 10, 420, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/img principal.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 380, 880, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBuscarMouseClicked
        // TODO add your handling code here:

        ListaBusqueda control2 = new ListaBusqueda(usuario, productotxt.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelBuscarMouseClicked

    private void LabelIngresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelIngresaMouseClicked
        // TODO add your handling code here:
        IniciaSesion control2 = new IniciaSesion(usuario);
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelIngresaMouseClicked

    private void productotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productotxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Registro control2 = new Registro(usuario);
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void L1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_L1MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, L1.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_L1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l2.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l3.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        ListaBusqueda control2 = new ListaBusqueda(usuario, l4.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l5.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l6.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
        ListaBusqueda control2 = new ListaBusqueda(usuario, l7.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l8.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l9.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l9MouseClicked

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l10.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l10MouseClicked

    private void l11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l11MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l11.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l11MouseClicked

    private void l12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l12MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l12.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l12MouseClicked

    private void l13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l13MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l13.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l13MouseClicked

    private void l14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l14MouseClicked
        // TODO add your handling code here:
        ListaBusqueda control2 = new ListaBusqueda(usuario, l14.getText());
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel LabelBuscar;
    private javax.swing.JLabel LabelIngresa;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField productotxt;
    // End of variables declaration//GEN-END:variables
}
